### ISSUE TITLE
I think the results of diff should have indices while some items just moved to a new position

### ISSUE THREAD

**Issue by lexrus** [jflinter/Dwifft#1]
After comparing `["a", "b", "c", "d"]` to `["c", "b", "a"]` we should know how to transform the first array into the second and vice versa. I mean we should get something like this:

``` swift
{
  $0.moveTo(2)
  $1.same()
  $2.moveTo(0)
  $3.delete()
}
```

So that it's possible to move a UITableViewCell to a new position when needed.

**Comment by jflinter** [comment]
After thinking about this for a while, I believe there are two separate pieces here.

First, there isn't enough information encoded in an `ArrayDiffResult` - it contains the index that needs to change, but not the actual value that needs inserting/deleting. In other words, given `x: [T]` and y: [T]`, the result of `x.diff(y)` should be enough on its own to transform x into y. This makes a lot of sense, and I've implemented it. `x.diff(y)` will now return a `Diff<T>` such that `x.apply(diff) == y`. (You can even call `diff.reversed()`, such that `y.apply(diff.reversed()) == x`.

Second, you're looking for a move operation of sorts in addition to insertion and deletion. While this is certainly possible (see http://docs.lib.purdue.edu/cgi/viewcontent.cgi?article=1377&context=cstech for a possible implementation), I don't think this makes any sense for Dwifft. Essentially, you can consider a move operation to consist of a simultaneous insertion and deletion, so this would be an optimization at best. This on its own isn't a reason to not do it - I'd be happy to optimize the algorithm further. The reason not to do it is that `UITableView` and `UICollectionView` don't expose any kind of batch `moveRowsAtIndexPaths:toIndexPaths:` method (they only expose `moveRowAtIndexPath:toIndexPath:`, which does one at a time, and (I strongly suspect) simply uses `insertRowsAtIndexPaths: and `deleteRowsAtIndexPaths:` under the hood). Thus, the potential savings that could be gained are pretty limited and (I'd argue) not worth the complexity they'd add to this code.

Hope that answers your questions. I would encourage you to take a look at the `Array.apply` method defined in `Dwifft.swift`, though, as I think it'll give you most of what you're looking for.

**Comment by aranasaurus** [comment]
Sorry to dust off an old issue, but `UICollectionView`'s `moveRowAtIndexPath:toIndexPath:` animates the move differently than calling `deleteItemsAtIndexPaths` followed by `insertItemsAtIndexPaths`, which would be why _I_ would want that to be a thing that Dwifft supported :)

**Comment by tonyarnold** [comment]
I came here to request the same thing — in addition to:

```swift
case Insert(Int, T)
case Delete(Int, T)
```

It would be really helpful to have moves recorded discretely:

```swift
case Move(Int, Int, T)
```

**Comment by jflinter** [comment]
@aranasaurus - your point about UICollectionView is a good one. I'll do some experimentation here when I have some time, but it probably won't be any time soon.
