### ISSUE TITLE
Does not work with tableView with sections.

### ISSUE THREAD

**Issue by niilohlin** [jflinter/Dwifft#24]

**Comment by FranciscoAmado** [comment]
Hi @niilohlin 

As is written in _Dwifft+UIKit.swift_ if you wish to use a multi section table, you can implement a DwifftCalculator for each section. You will also need to force the sectionIndex of the DwifftCalculator to match the section you'll be editing on.

GL

**Comment by jflinter** [comment]
Thanks @FranciscoAmado. See also #18.
