### ISSUE TITLE
Swift 2/Xcode 7 Support

### ISSUE THREAD

**Issue by natestedman** [jflinter/Dwifft#3]
I've converted the framework to compile in Xcode 7, with Swift 2: https://github.com/jflinter/Dwifft/compare/master...natestedman:swift2

I suppose that Swift 2 changes the Xcode 7 `pbxproj` changes are separate concepts, but Xcode really really likes making those project file changes. I tried to keep the commits atomic though, so they could be split out if desired. I don't believe it's possible to open a pull request for a new branch, so I'm creating this as an issue since it's incompatible with Swift 1.2.

On a separate branch, I made additional changes that remove the `LCS` and `Diff` classes and replace them with extensions of `Array`, constrained to `Element: Equatable`: https://github.com/natestedman/Dwifft/compare/swift2...swift2-extension

It might be possible to make the extensions more generic by having `CollectionType` extended instead, but I'd need to look into that more.

**Comment by jflinter** [comment]
Cool, thanks so much @natestedman, those were literally the exact changes I wanted to make once swift 2 was released. I just created PRs for both of your branches and merged them.

**Comment by natestedman** [comment]
Thanks for merging!
