### ISSUE TITLE
Error on Carthage build -> DwifftTests

### ISSUE THREAD

**Issue by IvoPintodaSilva** [jflinter/Dwifft#40]
error: overriding instance method must be as accessible as its enclosing type.

Errors are on: 
- insertRows
- deleteRows
- insertItems
- deleteItems

I have cloned the repo, built it and ran the tests with no problem. However it always fails the perform the Carthage build.

**Comment by jflinter** [comment]
I believe this should be fixed if you specify the latest version, 0.5, in your Cartfile.
