### ISSUE TITLE
tvOS scheme

### ISSUE THREAD

**Issue by papertigers** [jflinter/Dwifft#43]
Hey do you mind adding a tvOS scheme to the project? There shouldn't be any reason that it won't work out of the box that I can think of.  Thanks! 

*** Skipped building Dwifft due to the error:
Dependency "Dwifft" has no shared framework schemes for any of the platforms: tvOS

**Comment by papertigers** [comment]
Just forked and tested.  Everything builds just fine.

**Comment by jflinter** [comment]
Sure, mind submitting a PR for this?






On Tue, Nov 15, 2016 at 8:27 AM -0800, "Michael Zeller" <notifications@github.com> wrote:












Just forked and tested.  Everything builds just fine.

**Comment by romainbiard** [comment]
Hello,
I did it #62

cheers,
Romain
