### ISSUE TITLE
Docs link SSL cert issue

### ISSUE THREAD

**Issue by iwasrobbed** [jflinter/Dwifft#53]
Just a heads up, getting this when I visit the `https` version of your docs linked in the readme:

<img width="654" alt="screen shot 2017-04-15 at 8 12 54 am" src="https://cloud.githubusercontent.com/assets/317671/25064647/591e5156-21b3-11e7-8ee2-f0e67941328e.png">

**Comment by jflinter** [comment]
Oh, yikes, not a good look, thanks for the heads up!

**Comment by jflinter** [comment]
👍 fixed
