### ISSUE TITLE
Demo Usage in Readme

### ISSUE THREAD

**Issue by nevillco** [jflinter/Dwifft#61]
I think it would help people trying to integrate this repo in a project a lot if there was a sample use case.

**Comment by jflinter** [comment]
Want to write it?

**Comment by nevillco** [comment]
Yeah, I'll see what I can get done this weekend.

**Comment by jflinter** [comment]
Awesome, thank you! Happy to review.

**Comment by NSExceptional** [comment]
I don't think @nevillco is going to write it. For what it's worth, as someone looking for a diffing library, I'm not even considering using this one because the readme is a giant wall of text with no example code. I really recommend adding some example code.

**Comment by irace** [comment]
@NSExceptional Want to write it?

**Comment by NSExceptional** [comment]
No. If the creator cares if anyone will use his library, then he should write it himself.

**Comment by NSExceptional** [comment]
Just some advice.

**Comment by irace** [comment]
I don’t want to speak for @jflinter, but I highly doubt that he’s trying to cater to developers with this attitude, or have them be part of the Dwifft community.

**Comment by NSExceptional** [comment]
I see where you're coming from, but I think it is entirely the wrong response to ask someone else to write sample code for your own library when they ask for some. I don't have time to do it for him.  If he doesn't feel that he needs any, then it's no problem.

**Comment by jack-stripe** [comment]
@NSExceptional - there is literally a folder full of example code for this library, which I took great care to write and comment. Please do as you suggest and go bug another developer with your lazy, entitled attitude.
