### ISSUE TITLE
Support for Set<Equatable> collection type

### ISSUE THREAD

**Issue by numen31337** [jflinter/Dwifft#66]
There is a bunch of cases where we need to compare two sets of data and deal with their diff but here we forced to convert these collections to arrays and obviously use a heavier algorithm to deal with them. This can be achieved with the basic Swift Set operations like subtracting but I would really like to see such option in this library.

**Comment by jflinter** [comment]
Hmm, I'm a bit confused by what you're looking for. I think order of insertions/deletions is the primary use case for Dwifft. If you're looking for the series of changes to make to convert set `a` into set `b`, couldn't you just say `let insertions = b - a; let deletions = a - b`?

**Comment by numen31337** [comment]
Yes, that's right. In my particular case, I just wanted to be consistent in my code base and use the same `[DiffStep<T>]` output to update the database for both Sets and Arrays.

**Comment by jflinter** [comment]
Ah, ok. I think that's reasonable - would be happy to accept a PR that did this (I think it'd be pretty short/straighforward...)
