### ISSUE TITLE
[RFC] Make `Dwifft` an enum, not a struct

### ISSUE THREAD

**Issue by jessesquires** [jflinter/Dwifft#67]
It looks like `Dwifft` is only used as a namespace:
https://github.com/jflinter/Dwifft/blob/master/Dwifft/Dwifft.swift#L79

The problem with a `struct` is that it can be instantiated, `Dwifft()`. This isn't a problem now, since there are no instance members, but it is a bit awkward.

Changing this to `enum Dwifft` (with 0 cases) provides the same effect of namespacing, except you *cannot* instantiate an `enum`. 😄 

See also:

- https://www.natashatherobot.com/swift-enum-no-cases/
- http://ericasadun.com/2016/07/18/dear-erica-no-case-enums/

**Comment by jflinter** [comment]
That makes a lot of sense, thanks for the proposal! I'd happily accept a PR
making this change.
