### ISSUE TITLE
Direct access to Diff<T>

### ISSUE THREAD

**Issue by jersonperpetua** [jflinter/Dwifft#7]
Maybe I'm missing something, but is there a more direct way of getting into the diff other than through `Array.apply(_:)` and the various UIKit extensions? Looking at the public API, `DiffStep<T>` is exposed but the properties in `Diff<T>` are not; so maybe this is a mistake? If so, I can provide a PR.

I'm asking this because I have a use case that requires consuming the diff results on a lower-level layer that hides the diff'ing implementation from the UI.

**Comment by jflinter** [comment]
Just fixed this in 36aba1983a718ad76fd177f7313b8eadb4a5a110, thanks for the catch! (I'm going to hold off on cutting a version for now though since it's a pretty minor change, and there's some other stuff I'll want to add soon.)

**Comment by jersonperpetua** [comment]
Thanks! I'm not sure I agree with exposing more of `DiffStep<T>` than the previous version has though. Extracting values associated with enums outside of `switch` statements (i.e., `if case let .Insert(index, value) { ... }`) is now allowed in Swift 2.0 and up. Just my opinion though, I just think the API looks cleaner without all the other stuff.

**Comment by jflinter** [comment]
Ah yeah, that sounds reasonable. Re-privatized all that stuff on master.



—

**Comment by jersonperpetua** [comment]
Thank you very much for the fast response, and for an awesome framework! This and https://github.com/Wolox/ReactiveArray are a match made in heaven. :)

**Comment by jflinter** [comment]
Oh, interesting! I hadn't seen that project before. How exactly are you using it alongside Dwifft? Anything else I can do to make them play more nicely together?



—

**Comment by jersonperpetua** [comment]
Yup! I use ReactiveArray for collection properties in my view models (e.g., list of comments). Whenever the view model receives an update from the services layer (which is often a list of all comments up to that point), it calculates a diff between the old list of comments and the new one, and applies the steps into the `ReactiveArray` which, ultimately, reflects the changes to the associated `UITableView`/`UICollectionView`.

This looks like a long-winded way of doing it, and there are some projects that could benefit in using Dwifft directly (through `TableViewDiffCalculator`, for example). But, for my purposes, the extra separation between the layers allows me to sleep at night. :D

Pulling the `apply(_:)` to a protocol common to any indexed collection goes a long way in establishing interoperability between Dwifft and frameworks like ReactiveArray, IMO. Looking at Swift's `Array`, it seems like this common protocol could be `_ArrayType`, but I guess it is considered private judging from the underscore. Perhaps a custom protocol of our own that we can retrofit into both `Array` and `ReactiveArray` then?

**Comment by jflinter** [comment]
That seems reasonable. I wish Apple would clarify the meaning of the underscore a bit more. As you can see by my delayed reply, I'm pretty busy with work/travel for the next few weeks, but if you find something that works well here I'd be happy to merge a PR!
