### ISSUE TITLE
Small buildTable Refactor idea

### ISSUE THREAD

**Issue by KevinHock** [jflinter/Dwifft#79]
To prevent any future mistakes that might slip by PR review in the only spot Dwifft uses Unsafe*, could I make a PR to get the len of the args instead of passing the len in? Future xrefs to it can't pass something wrong in for the len https://github.com/jflinter/Dwifft/blob/master/Dwifft/Dwifft.swift#L281

// BEFORE
let table = MemoizedSequenceComparison.buildTable(lhs, rhs, lhs.count, rhs.count)
-->
// AFTER
let table = MemoizedSequenceComparison.buildTable(lhs, rhs)

// BEFORE
static func buildTable(_ x: [T], _ y: [T], _ n: Int, _ m: Int) -> [[Int]] {
-->
// AFTER
static func buildTable(_ x: [T], _ y: [T]) -> [[Int]] {
	n = x.count
	m = y.count
	...

**Comment by jflinter** [comment]
Thanks, fixed in https://github.com/jflinter/Dwifft/pull/82

**Comment by KevinHock** [comment]
Thanks :D
