### ISSUE TITLE
EXC_BAD_ACCESS in thread

### ISSUE THREAD

**Issue by guofei** [jflinter/Dwifft#8]
Xcode Version 7.1.1 (7B1005)

My code is like this:

```swift
dispatch_async(queue) {
	let s1 = get_a_string()
	let s2 = get_another_string()

	// size of a and b is about 1000
	let a = s1!.characters.split { $0 == "\n" }.map(String.init)
	let b = s2!.characters.split { $0 == "\n" }.map(String.init)

	let diff = a.diff(b) // crash in Array::diffFromIndices
}
```

![1](https://cloud.githubusercontent.com/assets/737136/11322130/cf696d30-911f-11e5-9a79-3c5b4c07e749.jpg)

**Comment by jflinter** [comment]
Thanks for the crash report - I'll see if I can reproduce it.



—

**Comment by jflinter** [comment]
I've been unable to reproduce this after a fair amount of testing. If you can write a test case in `DwifftTests.swift` that reliably fails and send me a PR with it, I'll be happy to take another look though.

**Comment by guofei** [comment]
I change recursion to for loop then everything is ok.
So I think the problem is that  the recursion may be too deep.

Example if i write:
```swift
	func testInThread() {
		let qos = Int(QOS_CLASS_USER_INITIATED.rawValue)
		let queue = dispatch_get_global_queue(qos, 0)
		dispatch_async(queue) {
			let string = String(count: 50, repeatedValue: Character("0"))
			let test = TestCase(string, string, string, "abc")
			let diff = test.array1.diff(test.array2)
			let printableDiff = diff.results.map({ $0.debugDescription }).joinWithSeparator("")
			XCTAssertEqual(printableDiff, test.expectedDiff, "incorrect diff")
		}
	}
```
the test will be failed

but if I write
```swift
	func testInThread() {
		let qos = Int(QOS_CLASS_USER_INITIATED.rawValue)
		let queue = dispatch_get_global_queue(qos, 0)
		dispatch_async(queue) {
			let string = String(count: 5000, repeatedValue: Character("0"))
			let test = TestCase(string, string, string, "abc")
			let diff = test.array1.diff(test.array2)
			let printableDiff = diff.results.map({ $0.debugDescription }).joinWithSeparator("")
			XCTAssertEqual(printableDiff, test.expectedDiff, "incorrect diff")
		}
	}
```
the test will be passed.

**Comment by kondratyevdev** [comment]
Please, help

**Comment by Janneman84** [comment]
Same problem here. For initialRows I have an array: [Int](0..<1150) (array of Ints from 0 through 1150). Then I randomly take like half of them out (amount doesn't seem to matter here) and set that to diffCalculator.rows. Then I get the screenshot like shown above.

In the debug window (left to log window) it says 1151 at table. Is this some out of bounds thing?

I may experiment some more, but what I tried is already the most basic usage I think.

**Comment by kondratyevdev** [comment]
@Janneman84 use https://github.com/Frugghi/SwiftLCS

**Comment by Janneman84** [comment]
Thanks that one works :). However it takes a couple of seconds to diff 1150 values :(. I probably should just forget about row animations for now :).
