### ISSUE TITLE
Podspec claims wrong version of swift

### ISSUE THREAD

**Issue by bdorfman** [jflinter/Dwifft#81]
Podspec sets a SWIFT_VERSION of 3.0.1 even though the latest release adds Swift4 support.

Also, I don't think setting that actually does anything in the resulting project that cocoapods generates, at least as of cocoapods 1.3.x (it overrides your setting to the latest version supported by xcode)

**Comment by jflinter** [comment]
Thanks; fixed in https://github.com/jflinter/Dwifft/pull/82
