### ISSUE TITLE
Dwifft 0.3 Is Not Available in the CocoaPods Spec Repo

### ISSUE THREAD

**Issue by paulrehkugler** [jflinter/Dwifft#9]
According to the releases on GitHub, 0.3 is the latest version, but only versions up to 0.2 are available via CocoaPods (see: https://cocoapods.org/pods/Dwifft). A Podfile like this will reproduce the issue.

```ruby
pod 'Dwifft', '0.3'
```

The likely solution to this issue is running `pod trunk push Dwifft.podspec`.

**Comment by jflinter** [comment]
Ah, sorry about that! I've pushed a 0.3.1 version (Cocoapods was 500'ing
when I tried pushing 0.3.0, so I bumped the version and that appeared to
fix things.)

**Comment by paulrehkugler** [comment]
Yup, that worked. Thanks!
