### ISSUE TITLE
Swift 4.2/Xcode 10 support

### ISSUE THREAD

**Issue by mkj-is** [jflinter/Dwifft#90]
I have noticed, that Dwifft cannot be compiled in Xcode 10 and Swift 4.2. Main issues are:

1. `UITableViewRowAnimation ` renamed to `UITableView.RowAnimation`.
2. `UITableViewStyle` renamed to `UITableView.Style`.
3. `UIApplicationLaunchOptionsKey` renamed to `UIApplication.LaunchOptionsKey `.
4. Some other details in example app and test dependencies.

How would you execute the transition to Swift 4.2? Do you think the changes need to be backward compatible? I can see few difficult issues to fix if you required the backward compatibility.

I am willing to help with the transition.

**Comment by jflinter** [comment]
@mkj-is I'd be happy to take a PR migrating to swift 4.2. No backwards compatibility necessary - I'll cut a new version of the library.
